name: Cerberus
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cerberus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run trufflehog
        run: |
          pip install trufflehog
          trufflehog --entropy=True .
      - name: Run git-secrets
        run: |
          pip install git-secrets
          git secrets --scan
      - name: Run semgrep
        run: |
          pip install semgrep
          semgrep --config=.semgrep.yml
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: cerberus-results
          path: cerberus-results.txt
